# Generated by Django 4.1.3 on 2023-09-10 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('student_id', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('profile_pic', models.CharField(blank=True, default='Profile Picture Set', max_length=10000, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('shs', models.CharField(blank=True, max_length=200, null=True)),
                ('bio', models.TextField(blank=True, max_length=10000000, null=True)),
                ('admission_year', models.IntegerField(default=2022)),
                ('level', models.CharField(blank=True, default='300', max_length=12, null=True)),
                ('semester', models.CharField(default='1', max_length=6)),
                ('email', models.EmailField(default='student@ug.gh', max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('department', models.ForeignKey(default='CPEN', on_delete=django.db.models.deletion.CASCADE, to='api.department')),
            ],
        ),
    ]
