# Generated by Django 4.1.3 on 2023-09-26 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=3)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('lecturer_id', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('profile_pic', models.CharField(blank=True, default='Profile Picture Set', max_length=10000, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(default='lect@ug.gh', max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('office', models.CharField(blank=True, max_length=20, null=True)),
                ('department', models.ForeignKey(default='CPEN', on_delete=django.db.models.deletion.CASCADE, to='api.department')),
            ],
        ),
    ]
