# Generated by Django 4.1.3 on 2023-09-30 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_registration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
