# Generated by Django 5.1.2 on 2024-10-10 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_project_assignment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='registration',
            name='course',
        ),
        migrations.AddField(
            model_name='registration',
            name='course',
            field=models.ManyToManyField(to='api.course'),
        ),
    ]
