# Generated by Django 5.1.2 on 2024-10-10 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_registration_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('student', 'course')},
        ),
        migrations.RemoveField(
            model_name='registration',
            name='course',
        ),
        migrations.AddField(
            model_name='registration',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.course'),
        ),
    ]
